### ISSUE TITLE
Missing dependency - which Google Analytics python package are you importing here?

### ISSUE THREAD

**Issue by rorito** [kronok/django-squeezemail#2]
tasks.py
from google_measurement_protocol import Event, report

**Comment by kronok** [comment]
Didn't think anyone was really messing with this project yet since it's just a collection of ideas that barely work, but you're working on a slightly older fork. I made a repo here for a new google analytics reporter that it uses: https://github.com/kronok/django-google-analytics-reporter

I've been re-writing a lot of the models lately and working towards a "funnel flow" rather than just pure drip day delays and querysets, so a lot of what you see in the repo is getting re-done if I can accomplish what I have in my head. I have it in a somewhat functional state at the moment, but not quite ready to replace what's here.

**Comment by rorito** [comment]
@kronok I think you've got some really good ideas here. Even what you have now is usable modulo a couple changes we made in our fork. We're thinking about deploying this at our startup, would you be interested in chatting about the direction of the project? My email is rory at tribute dot co, feel free to drop me a line. We'd be interested in collaborating on it.

**Comment by kronok** [comment]
Tossed you an email. I'm still getting my models figured out, and once I feel like I have a good base, I'll be pushing it to a new branch so you can check it out.
